# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.SmallIntegerField()),
                ('ranking', models.SmallIntegerField(choices=[(0, 'no ranking'), (1, 'rank 1'), (2, 'rank 2'), (3, 'rank 3'), (4, 'rank 4'), (5, 'rank 5')], default=0)),
                ('genre', models.SmallIntegerField(choices=[(0, 'none'), (1, 'Sci-Fi'), (2, 'Horror'), (3, 'Comedy'), (4, 'Crime'), (5, 'Drama'), (6, 'Nonfiction')], default=0)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('birthplace', models.CharField(max_length=64)),
                ('info', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='Movies_REST.Person')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='Movies_REST.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_director', to='Movies_REST.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenplay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_screenplay', to='Movies_REST.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='starring',
            field=models.ManyToManyField(through='Movies_REST.Role', to='Movies_REST.Person'),
        ),
    ]
